name: Build and Publish image to Docker hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set dynamic TAG variable
        id: set_tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env
        run: |
          mkdir -p ./
          printf 'VITE_KEYCLOAK_URL="${{ secrets.ENV_URL }}"
          VITE_KEYCLOAK_CLIENT_ID="${{ secrets.ENV_CLIENTID }}"
          VITE_KEYCLOAK_REALM="${{ secrets.ENV_REALM }}"
          VITE_CHAT_SERVICE_HUB_URL="${{ secrets.ENV_HUB }}"
          VITE_CHAT_SERVICE_URL="${{ secrets.ENV_CHAT_URL }}"
          VITE_USER_SERVICE_URL="${{ secrets.ENV_USER_URL }}"
          VITE_EVENT_SERVICE_URL="${{ secrets.ENV_EVENT_URL }}"' > ./.env

      - name: Verify .env
        run: cat ./.env

      - name: Build the Docker image
        run: docker build ./ --file ./Dockerfile -t lamersbart/pridr-frontend:$TAG

      - name: push image to hub
        run: docker push lamersbart/pridr-frontend:$TAG
